variables:
   TRIGGER_BRANCH: "1.0.0"
   TAG_RUNNER: default-runner

workflow:
  rules:
    - if: $CI_COMMIT_TAG

stages:
  - git_clone_job
  - helm-charts

git_clone_job: 
  stage: git_clone_job
  image: bitnami/git
  tags:
    - $TAG_RUNNER
  artifacts:
    paths: 
      - shared-pipelines/helm/pipelines/*
  script:
    - git clone --branch $TRIGGER_BRANCH https://${TT_TRIGGER_CI_NAME}:${TT_TRIGGER_CI_TOKEN}@gitlab.paas.turktelekom.com.tr/bulut/paas/devops/shared-pipelines.git

tt-common:
  stage: helm-charts
  trigger:
    include:
      - artifact: shared-pipelines/helm/pipelines/tt-helm-ci.yaml
        job: git_clone_job




