{{- if or .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tt-common.fullname" . }}
  labels:
    {{- include "tt-common.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config | nindent 2 }}
{{- end }}
