{{- if .Values.jkssecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tt-common.fullname" . }}
  labels:
    {{- include "tt-common.labels" . | nindent 4 }}
type: Opaque
data:
  speedsms.jks: {{ .Values.jkssecret.data | quote }}
{{- end }}
