{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tt-common.fullname" . }}
  labels:
    {{- include "tt-common.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ default "" .Values.secret.username | b64enc | quote }}
  password: {{ default "" .Values.secret.password | b64enc | quote }}
{{- end }}
