apiVersion: v1
kind: Service
metadata:
  name:  {{ include "tt-common.fullname" . }}
  labels:
    {{- include "tt-common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      targetPort: pod-port
      protocol: TCP
  selector:
    {{- include "tt-common.selectorLabels" . | nindent 4 }}
